### ISSUE TITLE
fontWeight support?

### ISSUE THREAD

**Issue by rdy** [aMarCruz/react-native-text-size#1]
Great module, looking forward to the iOS support.

Currently the module looks like it support measuring the `fontFamily` and `fontSize` only. The `fontWeight` could also effect the measured width, it would be great to add support for it.

**Comment by aMarCruz** [comment]
@rdy sure, I'll do that in next days.

...and I know nothing about iOS , hope someone from the community can submit a PR.

**Comment by aMarCruz** [comment]
@rdy , v2.0.0 is WIP on the [dev](https://github.com/aMarCruz/react-native-text-size/tree/dev) branch.

This is a complete rewrite and has improvements in the accuracy of the measurement in the devices and simulators in which I could test it. It supports `fontWeight`, `letterSpacing`, and other properties, all optional.

Now, the API of `measure()` for iOS is the same as that of Android and although some adjustments and tests are missing, it can already be used.

There are other functions to get font info that will be useful, but I still don't know how to homogenize the API on both platforms.

Please look at the [README](https://github.com/aMarCruz/react-native-text-size/blob/dev/README.md) on the dev branch.

For testing this new version please first unistall the current and add the new using the github url:
```bash
$ react-native unlink react-native-text-size && yarn remove react-native-text-size
$ yarn add aMarCruz/react-native-text-size#dev
$ react-native link react-native-text-size
```

..and I especially recommend that you clone the repo and run [the sample App](https://github.com/aMarCruz/react-native-text-size/blob/dev/example/README.md). It is an excellent way to understand how the changes in the properties affect the rendering, as well as to verify that rnTextSize works as it should.

I hope release the v2 on npm in a few days.

Closing this issue, ping me if you need help.
