### ISSUE TITLE
Using `measure` function synchronous

### ISSUE THREAD

**Issue by SaeedZhiany** [aMarCruz/react-native-text-size#10]
Is there a way to use `measure` function synchronous?

I have a function that I can not use `async` keyword in its signature and also using `this.setState` function is not feasible too, because this function is a utility among many other components and classes.

this below code return `Promise` that is not what I want. I want only the inner result object contains `width` and `height`.

```
export function renderedTextSize(text: string, size: number = 14, fontFamily: string = 'someFontName') {

  const fontSpecs: TSFontSpecs = {
    fontFamily: fontFamily,
    fontSize: size,
  };

  return TextSize.measure({
    text,
    ...fontSpecs,
  }).then((result: TSMeasureResult) => {
    return {width: result.width, height: result.height};
  }).catch((err) => {
    console.log('Error in measure:', err);
  });
}
```

**Comment by aMarCruz** [comment]
@SaeedZhiany , rn-text-size uses the same Android API as the [measure methods](https://facebook.github.io/react-native/docs/direct-manipulation#other-native-methods) of react native but without laying it, so it is not possible to return the results to the JS side synchronously, it needs to use promises or callbacks just like any other _native_ method in React Native.

You need to delay rendering until the result is available.
Thanks for your feedback, closing this issue now.

**Comment by gen1lee** [comment]
@aMarCruz it is possible to call functions synchronously with `RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD` (ios) and `@ReactMethod(isBlockingSynchronousMethod = true)` (android) and I think it would be better to add sync implementation.

**Comment by SaeedZhiany** [comment]
I'm not sure but I've recently heard (or read, I don't remember) that react-native Fabric architecture has been released. one of its major changes is the ability to call a native method from JS synchronous.

I believe using this feature will be the best way to implement it.

**Comment by SaeedZhiany** [comment]
I found it. you can read more about the fabric architecture from [this blog](https://reactnative.dev/blog/2022/03/15/an-update-on-the-new-architecture-rollout) and [this blog](https://reactnative.dev/blog/2022/03/30/version-068#opting-in-to-the-new-architecture).

**Comment by fukemy** [comment]
rn text size wait for the onlayout event, so it's does not work without promise.
for my case, I want to calculate the bubble text layout before render, and give height to some framework like recyclerListview, biglist. 
 And ok, it's not possible
