### ISSUE TITLE
'compile' is obsolete, warning in Android studio

### ISSUE THREAD

**Issue by dantman** [aMarCruz/react-native-text-size#12]
I'm using `implementation` as suggested in my own build file, however react-native-text-size is still using `compile` internally resulting in warnings when building.
```
.../node_modules/react-native-text-size/android/build.gradle:
Warning:Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

**Comment by aMarCruz** [comment]
@dantman thanks, I will release the next version soon.

Fortunately `compiler` only generates a warning while `implementation` prevents the build (for those who still use gradle 3).

**Comment by aMarCruz** [comment]
@dantman , sorry for the delay.

rnTextSize v2.1.1 and v3.0.0 is already in already in npm, v3 has a proper config for RN 0.57 and uses `compileOnly`, that should not generate warnings.

Both includes a new `lineInfoForLine` option for both Android and iOS.
See the [API here](https://github.com/aMarCruz/react-native-text-size/blob/master/README.md#tsmeasureresult).

Thanks for your feedback.
