### ISSUE TITLE
Line end feature parity on iOS

### ISSUE THREAD

**Issue by tuncaulubilge** [aMarCruz/react-native-text-size#13]
Android has a `lineEndForLineNo` that measures how many characters would fit into a given number of lines, but this is not yet supported in iOS. 

The issue was discussed in this pr:
https://github.com/aMarCruz/react-native-text-size/pull/11

**Comment by aMarCruz** [comment]
@tuncaulubilge yes, but a workaround exists and I have already the code, but no time to integrate it. I think in ~1 week I will do it.

**Comment by aMarCruz** [comment]
@tuncaulubilge , sorry for the delay.

rnTextSize v2.1.1 (for RN <0.57) and v3.0.0 (for RN >=0.57) is already in npm and includes a new `lineInfoForLine` option for both Android and iOS, based in your PR.

See the [API here](https://github.com/aMarCruz/react-native-text-size/blob/master/README.md#tsmeasureresult).
