### ISSUE TITLE
Get lineInfo for all lines

### ISSUE THREAD

**Issue by adamvert** [aMarCruz/react-native-text-size#14]
Would it be possible to have an option to get `lineInfo` for _every_ line, instead of having to specify a line number? I'm trying to calculate the optimal font size for laying out headlines, and I'd like to be able to choose a size that has a low variance in line widths. I could imagine, for example, that setting a value of `-1` for `lineInfoForLine` would then return an array of `lineInfo` objects.

**Comment by aMarCruz** [comment]
@adamvert , you can loop the headlines:

```js
const options = {
  ...fontSpecs,
  width: 99999,
  usePreciseWidth: true,
}
// headlines is an array
const promises = headlines.map(text => rnTextSize({ ...options, text }));
Promise.all(promises).then(sizes => {
  // 'sizes' array is 1:1 with headlines
})
```

The `measure` method is already heavy, when I have the time I will add a separate and more performant method for this, something like flatHeights, but for width.

Closing this issue now, I hope my sample helps.
Thanks for your feedback.
