### ISSUE TITLE
Source files not included with autolinking on iOS

### ISSUE THREAD

**Issue by sttz** [aMarCruz/react-native-text-size#16]
I just upgraded to react-native 0.60.0 and the `react-native-text-size` import became `null` in builds.

Checking the Xcode project, react-native did recognize the pod but didn't include the source files with it.

I don't know how it worked before but the `source_files` directive seems to be wrong: 

    s.source_files = 'RNTextSize/**/*.{h,m}'

After changing it to only `*.{h,m}` and re-running `pod install`, the source files were included in Xcode and the import works again.

**Comment by abegehr** [comment]
+1 can confirm that this is the issue and @sttz fixes it

**Comment by aMarCruz** [comment]
Thanks. I will test and publish a new version this weekend.

**Comment by aMarCruz** [comment]
@sttz , @abegehr , please try the latest version: `yarn add react-native-text-size@4.0.0-rc.1`
I don't have a Mac but hope it works.

**Comment by sttz** [comment]
Thanks, working fine here.
