### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by santiago** [aMarCruz/react-native-text-size#2]
Hi I'm trying to have this working on iOS, but at this point it is not even mounting as a NativeModule. I checked the code and it seems straightforward what it tries to achieve. You have a warning saying support for iOS is incomplete, do you have in mind already what needs be done to having it complete for iOS? I could help

**Comment by aMarCruz** [comment]
@santiago , we are developing for Android only at this time, but next week I will be receiving a Mac to start the development for iOS and I will be able to complement this module.

**Comment by pribeh** [comment]
Any update on the ios side?

**Comment by aMarCruz** [comment]
Sorry, not yet. Just this Monday is the first work-day of our iOS developer.

**Comment by pribeh** [comment]
@aMarCruz I understand :). We're hoping to utilize this when the ios version is ready.

**Comment by aMarCruz** [comment]
@rdy , v2.0.0 is WIP on the [dev](https://github.com/aMarCruz/react-native-text-size/tree/dev) branch.

Sorry by the delay. In these days it is difficult to find a good iOS programmer, so I had to study it myself (fortunately I started with C years ago).

well... v2 is a complete rewrite and has improvements in the accuracy of the measurement in the devices and simulators in which I could test it. It supports `fontWeight`, `letterSpacing`, and other properties, all optional.

Now, the API of `measure()` for iOS is the same as that of Android and although some adjustments and tests are missing, it can already be used.

There are other functions to get font info that will be useful, but I still don't know how to homogenize the API on both platforms.

Please look at the [README](https://github.com/aMarCruz/react-native-text-size/blob/dev/README.md) on the dev branch.

For testing this new version please first unistall the current and add the new using the github url:
```bash
$ react-native unlink react-native-text-size && yarn remove react-native-text-size
$ yarn add aMarCruz/react-native-text-size#dev
$ react-native link react-native-text-size
```

..and I especially recommend that you clone the repo and run [the sample App](https://github.com/aMarCruz/react-native-text-size/blob/dev/example/README.md). It is an excellent way to understand how the changes in the properties affect the rendering, as well as to verify that rnTextSize works as it should.

I hope release the v2 on npm in a few days.

Closing this issue, ping me if you need help.

**Comment by pribeh** [comment]
holy smokes – sounds like you've been busy. thank you for doing this. we really needed this as we're looking to speed up our chat flatlist with getitemlayout. using react-native-text-size seems like the only way to achieve this. we'll start testing it today.

**Comment by aMarCruz** [comment]
@pribeh yes, we all have the same problem with FlatList.

Just take into account that the measurement is a somewhat heavy process, so try to cache what you can and measure only the parts that change height (usually the text of the message).

By example, in parts where you know that one line will always be shown, measure the height of something like "Äj" and use it as the fix height of that lines in all the elements.

**Comment by pribeh** [comment]
From the documentation, it looks like flatheight is the preferred/optimized method for chat-based flatlists. Am I correct in assuming this?

**Comment by aMarCruz** [comment]
@pribeh yes, it is. In my case I have a list with cards, most of the parties have paddings and a number of fixed lines and I only need to measure them once. The changing part is the body of the message. When the data arrives from the back-end, I process it and call flatHeights and with the result I get the final height of each card.

Something like this:
```js
// "data" is an array with the data from the server
const bodies = data.map(o => o.body)

TextSize.flatHeights(bodies).then(heights => {
    heights.forEach((height, ix) => data[ix].height = fixedCardHeight + height))
})
// "fixedCardHeight" is the height of the fixed parts, measured in componentDidMount.
// Now we have the height ready to getItemLayout.
```

**Comment by aMarCruz** [comment]
@pribeh , the previous code is worng, bodies is in the `text` property of the options passed to flatHeights:
```js
options = {
  text: bodies,
  fontSize: 16,
  ...etc
}
TextSize.flatHeights(options).then( ...etc
```

sorry :)

**Comment by pribeh** [comment]
Thank you so much @aMarCruz. We will give this a go.

**Comment by aMarCruz** [comment]
TextSize v2.0.0 is already in npm and the master branch.
