### ISSUE TITLE
Method to detect bold text within normal text string

### ISSUE THREAD

**Issue by pribeh** [aMarCruz/react-native-text-size#25]
We have a number of instances where we have bold text within a normal text string.  Is there any method currently available to RNTS that can detect bolded text as such and measure it? If not, maybe we could add a simple [regex](https://www.regextester.com/95400) for bold text.

For example, currently, we use a library known as React Native Auto-link which permits the styling of hash-tagged terms as such: 

```
         <AutolinkComponent 
              style={styles.text}
              text={this.props.postText}
              hashtag="instagram"
              mention="twitter"
              linkStyle={{ fontWeight:'bold' }}
         />
```

**Comment by pribeh** [comment]
In the meantime, I've figured out that a workaround is to reduce the letter-spacing for the bolded text to roughly reflect the size of non-bolded text.

**Comment by aMarCruz** [comment]
Hi @pribeh .
Unfortunately, it is not possible for now.
It seems simple, but it is a complex operation that should have a margin of error less than one pixel.
Sorry.
