### ISSUE TITLE
Using it on React Native Web

### ISSUE THREAD

**Issue by Karansidds** [aMarCruz/react-native-text-size#33]
I want to use this module on react-native-web, but the following code 

`const { width: partialTextWidth } = await reactNativeTextSize.measure({
      text: text.slice(0, middle),
      fontSize: scaledFontSize,
      fontFamily,
      fontWeight,
});`

gives me this error: `TypeError: Cannot read property 'measure' of undefined`

`import reactNativeTextSize from 'react-native-text-size';`

When I console `reactNativeTextSize`, it shows `undefined`. I don't know what is causing the issue. Does anyone know how I can make this module work on react-native-web?

**Comment by eseQ** [comment]
@Karansidds have any solution?
