### ISSUE TITLE
the implementation in iOS project is total different from Android project.

### ISSUE THREAD

**Issue by xincubate** [aMarCruz/react-native-text-size#4]
the implementation in iOS project is total different from Android project.
it need args named "text","fontSize" in Android project , but these args would fail when you pass to iOS project. it need args named "texts" "width" and so on

**Comment by xincubate** [comment]
the results are different too

**Comment by aMarCruz** [comment]
@xincubate yes I know, I'm just refactoring this library :smiley:

The v2.0 will contain a `measure` function similar to that of Android and two new functions for iOS. In a few more hours it will be ready and published in npm.

(It will be necessary to uninstall the previous one before using the new one)

**Comment by aMarCruz** [comment]
@xincubate , v2.0.0 is WIP on the [dev branch](https://github.com/aMarCruz/react-native-text-size/tree/dev) and sorry by the delay, I had to study Objective-C by myself to do this...

well... v2 is a complete rewrite and has improvements in the accuracy of the measurement in the devices and simulators in which I could test it. It supports `fontWeight`, `letterSpacing`, and other properties, all optional.

Now, the API of `measure()` for iOS is the same as that of Android and although some adjustments and tests are missing, it can already be used.

There are other functions to get font info that will be useful, but I still don't know how to homogenize the API on both platforms.

Please look at the [README](https://github.com/aMarCruz/react-native-text-size/blob/dev/README.md) on the dev branch.

For testing this new version please first unistall the current and add the new using the github url:
```bash
$ react-native unlink react-native-text-size && yarn remove react-native-text-size
$ yarn add aMarCruz/react-native-text-size#dev
$ react-native link react-native-text-size
```

..and I especially recommend that you clone the repo and run [the sample App](https://github.com/aMarCruz/react-native-text-size/blob/dev/example/README.md). It is an excellent way to understand how the changes in the properties affect the rendering, as well as to verify that rnTextSize works as it should.

I hope release the v2 on npm in a few days.

Closing this issue, ping me if you need help.
